DELETE FROM CFCLASS WHERE CFCLASSID LIKE 'wos%' AND NOT CFCLASSID LIKE 'wos';
INSERT INTO CFCLASS_CLASS (CFCLASSSCHEMEID1, CFCLASSID1, CFCLASSSCHEMEID2, CFCLASSID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE)
SELECT CFCLASSSCHEMEID, CFCLASSID, 'researchArea', 'wos', 'hierarchy', 'belongsTo','1900-01-01 12:00:00','2099-12-31 12:00:00' FROM CFCLASS WHERE CFCLASSID LIKE 'wos%' AND NOT CFCLASSID LIKE 'wos';
