INSERT INTO COMMISSION (COMMISSIONID, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD)
SELECT 711, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD FROM COMMISSION WHERE COMMISSIONID = 11;

INSERT INTO COMMISSION (COMMISSIONID, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD)
SELECT 712, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD FROM COMMISSION WHERE COMMISSIONID = 12;

INSERT INTO COMMISSION (COMMISSIONID, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD)
SELECT 713, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD FROM COMMISSION WHERE COMMISSIONID = 13;

INSERT INTO COMMISSION (COMMISSIONID, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD)
SELECT 723, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD FROM COMMISSION WHERE COMMISSIONID = 23;

INSERT INTO COMMISSION (COMMISSIONID, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD)
SELECT 714, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD FROM COMMISSION WHERE COMMISSIONID = 14;

INSERT INTO COMMISSION (COMMISSIONID, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD)
SELECT 715, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA, SCIENTIFICFIELD FROM COMMISSION WHERE COMMISSIONID = 15;

INSERT INTO COMMISSION_COMMISSION (COMMISSIONID1, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE)
SELECT 711, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE FROM COMMISSION_COMMISSION WHERE COMMISSIONID1 = 11;

INSERT INTO COMMISSION_COMMISSION (COMMISSIONID1, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE)
SELECT 712, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE FROM COMMISSION_COMMISSION WHERE COMMISSIONID1 = 12;

INSERT INTO COMMISSION_COMMISSION (COMMISSIONID1, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE)
SELECT 713, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE FROM COMMISSION_COMMISSION WHERE COMMISSIONID1 = 13;

INSERT INTO COMMISSION_COMMISSION (COMMISSIONID1, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE)
SELECT 723, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE FROM COMMISSION_COMMISSION WHERE COMMISSIONID1 = 23;

INSERT INTO COMMISSION_COMMISSION (COMMISSIONID1, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE)
SELECT 714, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE FROM COMMISSION_COMMISSION WHERE COMMISSIONID1 = 14;

INSERT INTO COMMISSION_COMMISSION (COMMISSIONID1, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE)
SELECT 715, COMMISSIONID2, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE FROM COMMISSION_COMMISSION WHERE COMMISSIONID1 = 15;

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 711, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 1 and (CFCLASSID not like 'M2%' and  CFCLASSID not like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 711, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 11 and (CFCLASSID like 'M2%' or  CFCLASSID like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 712, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 2 and (CFCLASSID not like 'M2%' and  CFCLASSID not like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 712, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 12 and (CFCLASSID like 'M2%' or  CFCLASSID like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 713, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 3 and (CFCLASSID not like 'M2%' and  CFCLASSID not like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 713, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 13 and (CFCLASSID like 'M2%' or  CFCLASSID like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 723, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 23 and (CFCLASSID like 'M2%' or  CFCLASSID like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 723, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 3 and (CFCLASSID not like 'M2%' and  CFCLASSID not like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 714, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 4 and (CFCLASSID not like 'M2%' and  CFCLASSID not like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 714, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 14 and (CFCLASSID like 'M2%' or  CFCLASSID like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 715, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 5 and (CFCLASSID not like 'M2%' and  CFCLASSID not like 'M5%');

INSERT INTO MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID, RESEARCHAREA)
select RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, 715, RESEARCHAREA from MARC21RECORD_CLASS where COMMISSIONID = 15 and (CFCLASSID like 'M2%' or  CFCLASSID like 'M5%');
