ALTER TABLE FILE_STORAGE ADD COLUMN LICENSE VARCHAR(50) AFTER LENGTH;
ALTER TABLE FILE_STORAGE ADD COLUMN TYPE VARCHAR(50) AFTER LICENSE;
ALTER TABLE FILE_STORAGE ADD COLUMN NOTE VARCHAR(100) AFTER TYPE;
ALTER TABLE FILE_STORAGE ADD COLUMN DATEMODIFIED VARCHAR(50) AFTER LENGTH;
ALTER TABLE FILE_STORAGE ADD COLUMN FILENAMECLIENT TEXT AFTER FILENAME;

UPDATE FILE_STORAGE SET FILENAMECLIENT=FILENAME;

INSERT INTO FILE_STORAGE (RECORDID, FILENAME, FILENAMECLIENT, MIME, UPLOADER, LENGTH, DATEMODIFIED, LICENSE, TYPE, NOTE)
SELECT RECORDID, CONCAT('ju', FILENAME), FILENAMECLIENT, MIME, UPLOADER, LENGTH, DATEMODIFIED, null, 'preliminaryTheses', 'Public period finished!'
FROM FILE_STORAGE
WHERE DATEMODIFIED is not null and TYPE='document' and RECORDID in (SELECT RECORDID FROM FILE_STORAGE WHERE TYPE='report' and NOTE='Public period finished!')

INSERT INTO FILE_STORAGE (RECORDID, FILENAME, FILENAMECLIENT, MIME, UPLOADER, LENGTH, DATEMODIFIED, LICENSE, TYPE, NOTE)
SELECT RECORDID, CONCAT('ju', FILENAME), FILENAMECLIENT, MIME, UPLOADER, LENGTH, DATEMODIFIED, 'Temporary available', 'preliminaryTheses', null
FROM FILE_STORAGE
WHERE DATEMODIFIED is not null and TYPE='document' and RECORDID in (SELECT RECORDID FROM FILE_STORAGE WHERE TYPE='report' and NOTE is null)