INSERT INTO bibliography.COMMISSION (COMMISSIONID, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA)
SELECT COMMISSIONID, APPOINTMENTBOARD, APPOINTMENTDATE, MEMBERS, CFCLASSSCHEMEIDSCIENCEAREA, CFCLASSIDSCIENCEAREA FROM bibliography2.COMMISSION mc2 WHERE mc2.COMMISSIONID in (51, 52, 53, 54, 55, 56);

INSERT INTO bibliography.MARC21RECORD_CLASS (RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID)
SELECT RECORDID, CFCLASSSCHEMEID, CFCLASSID, CFSTARTDATE, CFENDDATE, COMMISSIONID FROM bibliography2.MARC21RECORD_CLASS mc2 WHERE mc2.COMMISSIONID in (51, 52, 53, 54, 55, 56);